services:
  webapp:
    build:
      context: webapp
      dockerfile: docker/prod/Dockerfile
      # Décommenter pour passer les variables au build Vite :
      # args:
      #   VITE_MAPBOX_TOKEN: ${VITE_MAPBOX_TOKEN}
    container_name: homepedia-webapp-prod
    ports:
      - "80:80"
    restart: unless-stopped

  api:
    build:
      context: api
      dockerfile: docker/prod/Dockerfile
    container_name: homepedia-api-prod
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    restart: unless-stopped
