default:
    just --list

up ENV:
    #!/bin/bash
    if [ "{{ENV}}" = "dev" ]; then
        docker compose -f compose.dev.yml up --detach
    elif [ "{{ENV}}" = "prod" ]; then
        docker compose -f compose.prod.yml up --detach --build
    else
        echo "{{ENV}}: Accepted values are: 'dev', 'prod'." >&2
        exit 1
    fi

down ENV:
    #!/bin/bash
    if [ "{{ENV}}" = "dev" ]; then
        docker compose -f compose.dev.yml down
    elif [ "{{ENV}}" = "prod" ]; then
        docker compose -f compose.prod.yml down
    else
        echo "{{ENV}}: Accepted values are: 'dev', 'prod'." >&2
        exit 1
    fi

logs ENV:
    #!/bin/bash
    if [ "{{ENV}}" = "dev" ]; then
        docker compose -f compose.dev.yml logs --follow
    elif [ "{{ENV}}" = "prod" ]; then
        docker compose -f compose.prod.yml logs --follow
    else
        echo "{{ENV}}: Accepted values are: 'dev', 'prod'." >&2
        exit 1
    fi
